### ISSUE TITLE
Translation request

### ISSUE THREAD

**Issue by Vital-Fernandez** [TurtleShip/webtoon-crawler#4]
Thank you very much fo your work

Are you planning to add an english translation?

**Comment by TurtleShip** [comment]
Hi, @Delosari 
Thanks so much for your interest!

I actually started working on it a couple weeks ago. Only this time, I am putting it on [Windows Store](https://www.microsoft.com/en-us/store/p/linewebtoon/9nxs7xr34l4m) 😄   I hope you use Windows 10 devices. ( PC/tablet/mobile)

Since Naver Korean site does not have international version, I created a crwaler for its international version : http://www.webtoons.com

As you can see from the feature note, it currently does not support downloading webtoons directly to your PC. However, I am close to finishing the feature and will push the feature in 2~10 days of time. I will update this thread once I push out the feature.

My plan is to make the Windows Store version the official one, and add support for all possible languages there :) 

I will update README of this repository as well to point to the official app once I add Korean support there, too. If you want to track my progress or request additional features, please visit https://trello.com/b/3kF4a3eb/linewebtoon-crawler

Thanks again for your interest!

**Comment by Vital-Fernandez** [comment]
Wow it looks great! I will be looking forward for all these features :)

**Comment by TurtleShip** [comment]
@Delosari  Out of curiosity, what kind of Windows 10 devices (PC, tablet, or mobile) do you use?

**Comment by TurtleShip** [comment]
Hi, @Delosari 

An English version of my app is on Windows Store now 😄 
https://www.microsoft.com/en-us/store/p/linewebtoon/9nxs7xr34l4m
